[drive]
media = "disk"
file = "./build/main_floppy.img"

[machine]
type = "pc"

[memory]
size = "1G"
# should be able to run on a 1 GB system, to fullfill the dream of running on OLD systems

[device "video0"]
driver = "VGA"
